Pay_Your_Rent = //*[@content-desc="rent_pay"]
House_Rent = //*[@content-desc="rent_category_0"]
House_Rent_Clicked = //*[@content-desc="rent_category_0_active"]
Rent_amount = //*[@content-desc="rp_amount_input_input"]
Amount_Words = //*[@content-desc="rp_amount_input_in_word"]
Rent_field_Error = rp_amount_input_error
Next_Button = //*[@content-desc="rp_flow_cta"]
True_caller = //*[@resource-id='com.truecaller:id/confirm']
True_caller_diff_Number = //*[@resource-id='com.truecaller:id/continueWithDifferentNumber']
Enter_Phone_Number = //android.widget.EditText[@text='Enter Phone Number']
Submit_CTA  = //*[@content-desc="onboarding_login_clicked"]
Enter_OTP =  //*[@content-desc="otp_input"]/*/*/*
Verify_CTA = //*[@content-desc="otp_verify"]
UPI_Text_Field = //*[@content-desc="rp_main_input_input"]
Re-enter_bank_ac = //*[@content-desc="rp_reaccount_input_input"]
UPI_Name    =  //*[@content-desc="rp_main_input_detail"]
Landlord_Name = //*[@content-desc="rp_lanlord_name_input_input"]
Phone_number = //*[@content-desc="rp_lanlord_contact_input_input"]
PAN_ID =  //*[@content-desc="rp_pan_input_input"]
User_Name = //*[@content-desc="rp_tenant_name_input_input"]
Email_field = //*[@content-desc="rp_tenant_email_input_input"]
PIN_Code = //*[@content-desc="rp_pincode_input_input"]
City = //*[@content-desc='rp_city_input']
Month = //*[@content-desc="rent_month_2"]
Payment_modal = //*[@content-desc="rp_pm_0_active"]/*[@index='1']
New_Payment_modal = //*[contains(@content-desc,'rp_pm_')]/*[@index='1']
Total_Pay = //*[@content-desc="rp_modal_cta"]
How_it_Works = //*[@content-desc="rp_hiw"]
How_It_Works_Modal = //*[@text ='How it works']
FAQs_LP = //*[@content-desc="rp_faq"]
FAQ_Modal = //*[@text ='Some questions asked']
FAQ_Validation = //*[starts-with(@text,'Referral code')]
FAQ_scroll = //*[@content-desc="faq_5_expanded"]
IFSC_Field = //*[@content-desc="rp_ifsc_input_input"]
Branch_Name = //*[@content-desc="rp_ifsc_input_detail"]
Contact_Icon = //*[@content-desc="rp_lanlord_contact_picker"]
Phone_2 = //*[@content-desc="rp_lanlord_contact_input_input"]
Apply_CTA = //*[@content-desc="referral_cta"]
Valid_Code = //*[@content-desc="referral_error"]
Enter_code = //*[@content-desc='referral']/following-sibling::*/*
Convenience_fee = //*[@content-desc="rp_modal_cta_conv"]/*[@text='Payment Details']
Convenience_collapsed = //*[@content-desc='rp_modal_cta_conv']/*[starts-with(@text,'Convenience fees')]
Cancel_CTA = //*[@content-desc="rp_flow_cta_cancel"]
Edit_CTA = //*[@content-desc="rp_header_edit_1"]
Save_CTA = //*[@content-desc="rp_flow_cta"]
X_button = //*[@content-desc="rp_close"]
Exit_button = //*[@content-desc="exit_modal_exit"]
Dont_Exit_CTA = //*[@content-desc="exit_modal_dont_exit"]
Logout = //*[@text='Logout']
RazorPay_Modal = //*[@resource-id='modal-close']
#########################################################################################################################################################################

Pay_Rent_Tab = //*[@content-desc="home_pay rentButton"]
FAQs = //*[@content-desc="rp_home_faq_cta"]
Coins = //*[@content-desc="rp_home_coin_view"]
Refer_&_Earn_Passbook = //*[@text='Refer & Earn Passbook']
FAQ_Refer_Earn_Validation = //*[starts-with(@text,'Referral code')]
Pay_Again_CTA = //*[@content-desc="rp_home_pay_again_cta"]
Payment_Details_Screen = //*[@content-desc="rp_ru_title"]
Submit_reciept_CTA = //*[@text='Submit']
Housing_Pay_Rent_header =  //*[@text='Housing Pay Rent']
Code_Copied_Text = //*[@content-desc="reward_open_copied"]
Verified_Tag = //*[@content-desc='rp_main_input_verify']/*[@index='1']
landlord_name_edit = //*[@content-desc='rp_lanlord_name_input_input' and @text='']
landlord_contact_edit = //*[@content-desc='rp_lanlord_contact_input_input' and @text='']
tenant_name_edit = //*[@content-desc='rp_tenant_name_input_input' and @text='']
tenant_email_edit = //*[@content-desc='rp_tenant_email_input_input' and @text='']
tenant_pin_edit = //*[@content-desc='rp_pincode_input_input' and @text='']
rent_amount_edit = //*[@content-desc='rp_amount_input_input' and @text='']
Save_detail_edit = //*[@text='Save Detail']
Payment_Mode = //*[@content-desc='rp_ru_pm_edit']/preceding-sibling::*[@index='1']
Transferring_to = //*[starts-with(@text,'Transferring to')]
Living_at = //*[starts-with(@text,'Living at')]
T&C = //*[@text='Term of Use Policy']
Total_pay = //*[@content-desc='rp_ru_cta']/*[starts-with(@text,'Total Pay')]
Total_payable_payment_modal = //*[@content-desc='rp_modal_cta_conv']/*[@index='8']
TotalPay_CTA_Payment_modal = //*[@content-desc='rp_modal_cta']/*[starts-with(@text,'Total Pay')]
Amount_from_Pop_UP = //*[@content-desc='rp_ru_cta_conv']/*[@index='3']
Amount_from_Pop_UP_2 = //*[@content-desc='rp_ru_cta_conv']/*[@index='5']
FAQ_Back_Button = //*[@text='Housing Pay Rent']/preceding-sibling::*/*
Premium_Transaction_Screen = //*[@text='There are no Premium Transactions']
Pay_Rent_CTA_Tr_screen = //*[@content-desc='tran_Pay Rent']
Help_Support = //*[@content-desc='help_support']
Delay_in_payment_label = //*[@text='Delay in payment']
Help_Screen_Submit_CTA = //*[@content-desc='help_support_submit']
Help_Support_back_button = //*[@text='Help and Support']/preceding-sibling::*
See_Status_CTA = //*[@text='See Status']
Detail_link_failed_card = //*[@content-desc='tran_Payment failed']/following-sibling::*[@content-desc='tran_detail_clicked']
KYC_Submit_CTA = //*[@content-desc='kyc_submit_cta']/*
PAN_Error = //*[@content-desc='kyc_pan_input_error']
DL_Error = //*[@content-desc='kyc_dl_input_error']
Voter_Error = //*[@content-desc='kyc_voter_input_error']
date_picker_cancel = //*[@content-desc='date_picker_cancel']
date_picker_select= //*[@content-desc='date_picker_select']
date_picker_current_date = //*[@content-desc='date_picker_current_date']
KYC_Voter_Edit = //*[@content-desc='kyc_voter_input_input']
Edit_1 = //*[@content-desc="rp_ru_step3_edit_cta"]
Edit_2 = //*[@content-desc="rp_ru_step2_edit_cta"]
Go_to_Transactions_CTA = //*[@content-desc="rp_home_transactions_cta"]
Refer_Now = //*[@content-desc="rp_home_referral_cta"]
Toast_Message = //android.widget.Toast[1]
COPY = //*[@content-desc="reward_0_copy"]
Total_Pay_CTA = //*[@content-desc="rp_ru_cta"]/*[starts-with(@text,'Total Pay')]
PAN_Card = //*[@content-desc="kyc_pan"]
Payment_Method_Edit = //*[@content-desc="rp_ru_pm_edit"]
Cancel_Button = //*[@content-desc="undefined_cancel"]
Expand_CTA = //*[@content-desc='rp_ru_cta_conv']/*[starts-with(@text,'Convenience fees')]
Collapse_CTA = //*[@content-desc="rp_ru_cta_conv"]/*[@text='Payment Details']
Pay_Rent_CTA = //*[@content-desc="rp_ru_cta"]
My_Transactions = //*[@content-desc="my_trans"]
Date_Element = //*[@content-desc="my_trans_date"]
Transaction_Sucessful = //*[@content-desc="tran_Payment processed to landlord"]
Details_CTA = //*[@content-desc='tran_Payment processed to landlord']/following-sibling::*[@content-desc='tran_detail_clicked']
Money_not-received = //*[@text='Money not received yet?']
Share_CTA = //*[@text='Share Receipt']
download_cta = //*[@text='Download Receipt']
Retry_Payment_CTA = //*[@text='Retry Payment']
Enter_PAN_Number = //*[@content-desc="kyc_pan_input_input"]
DOB = //*[@content-desc="date_picker_input_input"]
Change_link = //*[@content-desc="kyc_change_cta"]
Voter_ID = //*[@content-desc="kyc_voter"]
Licence_Number = //*[@content-desc="kyc_dl_input_input"]
Home_screen_Rewards_scroll = //*[@content-desc="reward_scrollview"]/*/*/*/*
Email_login_screen = //*[@content-desc="login_input_input"]
Password_login_screen = //*[@content-desc="login_password_input"]
Sign_In_CTA = //*[@content-desc='login_submit']
Edge_bottom_tab = //*[@content-desc='Edge']
Profile_bottom_tab = //*[@content-desc='home_profileButton']
########################################################################################################################################################################

Refer>Earn>Save_CTA = //*[@content-desc='rp_home_referral_view']/*/*[@index='1']
Refer_earn_screen = //*[@text='Refer & Earn']
Referal_code = ref_full_copied
Referal_code_copied = ref_modal_copied
Whats_app_CTA = //*[@content-desc='ref_share']
More_CTA = //*[@content-desc='referal_more']
FAQ_expanded = //*[@content-desc='faq_0_expanded']
FAQ_expanded_ID = faq_0_expanded
Earn_coins_now_CTA = //*[@text='Earn coins now']
Refer_earn_Passbook_screen = //*[starts-with(@text,'Refer & Earn')]
Coins_Count = ref_trans_coins
See_all_rewards_link = //*[@content-desc='view_all_rewards_cta']
Coupons_Count_Active = //*[@content-desc='rews_active_coupon']
My_Rewards = //*[@content-desc='rewards_bck']/following-sibling::*[@text='My Rewards']
Active_Coupon = //*[@content-desc='rews_active_coupon' and starts-with(@text,'Active')]
Expired_Coupon = //*[@content-desc='rews_active_coupon' and starts-with(@text,'Expired')]
Coins_count_unused = //*[@content-desc='coin_unused']/*[ends-with(@text,' Coins available')]
Coins_count_after_use = //*[@content-desc='coin_used']/*[ends-with(@text,' Coins available')]
Total_Amount_Before = //*[@content-desc='rp_ru_cta_conv']/*[@index='8']
Total_Amount_After = //*[@content-desc='rp_ru_cta_conv']/*[@index='10']
Congrats = //*[@content-desc='coin_used']/*[starts-with(@text,'Congrats! You saved')]
New_line_after_using_coin_1 = //*[@content-desc='rp_ru_cta_conv']/*[@text='Housing Coin Discount']
New_line_after_using_coin_2 = //*[@content-desc='rp_ru_cta_conv']/*[starts-with(@text,'-')]
refer_now = //*[@content-desc='ref_empty_clicked']
Login_with_Number = //*[@content-desc="login_number"]
########################################################################################################################################################################

Edge_Tab = //*[@content-desc="home_servicesButton"]
Title = //*[starts-with(@text,'All Services')]
Edge_PayRent = //*[@text='Pay Rent' and @index = '1']
Edge_RA = //*[@text='Rent Agreement']
Testimonial_cards = //*[@content-desc='0_testimonial_card']
News_Articles = //*[@content-desc='0_article_card_clicked']
Articles_heading = //*[@text='ARTICLES']
Support_heading = //*[@text='SUPPORT']
EDGE_Home_Interiors_FAQs = //*[@content-desc="Home Interiors_eLanding_faq"]
EDGE_PayRent_FAQs = //*[@content-desc="Pay Rent_eLanding_faq"]
EDGE_RA_FAQs = //*[@content-desc="Rent Agreement_eLanding_faq"]
EDGE_PayRent_First_FAQs = //*[@content-desc="faq_0"]
EDGE_HI_First_FAQs = //*[@content-desc="HI_faq_0"]
EDGE_RA_First_FAQs = //*[@content-desc="RA_faq_0"]
EDGE_HI_FAQ_scroll = //*[@content-desc="HI_faq_6_expanded"]
EDGE_RA_FAQ_scroll = //*[@content-desc="RA_faq_6_expanded"]
RA_FAQ_Validation = //*[starts-with(@text,'Digital signatures')]
HI_FAQ_Validation = //*[starts-with(@text,'One of the most')]







########################################################################################################################################################################
# Account details like emails and Password

#Pay_Rent_flow_for_new user.feature
Email_New_user = cena@mailinator.com

#Pay_Rent_Home_Page.feature
Email_scenario_1 = orange@mailinator.com
Email_scenario_7 = test3@mailinator.com
KYC_Account = khusi@mailinator.com
#Above KYC_Account is used for Scenario 8 & 9
Password = qwerty
#Note: Same KYC_Account is being used in Refer_&_Earn_Module.feature for Scenario 1 & 2

# _reusable_methods.java
Phone_Number = 9871739261
OTP = 111111



########################################################################################################################################################################