Student_Title_Page = Student | BrightChamps
Login_with_Password_CTA = //*[@type='button']/span[contains(text(),'Login with Password')]
Sign_in_CTA = //*[@type='submit']/span[contains(text(),'Sign In')]
Email_field = //*[@type='text']
Password_field = //*[@type='password']
Student_Home_page = //*[text()='Profile']
Referral_modal = //*[@data-testid='CloseIcon']
Account_Select_Page = //*[@type='button']/span[contains(text(),'View Dashboard')]
