Student_Title_Page = Student | BrightChamps
Login_with_Password_CTA = //*[@type='button']/span[contains(text(),'Login with Password')]
Sign_in_CTA = //*[@type='submit']/span[contains(text(),'Sign In')]
Email_field = //*[@type='text']
Password_field = //*[@type='password']
Profile_button = //*[text()='Profile']
Referral_modal = //*[@data-testid='CloseIcon']
Account_Select_Page = //*[@type='button']/span[contains(text(),'View Dashboard')]
Edit_Profile = //*[contains(text(),'Edit Profile')]
triple_dots = //button[starts-with(@class,'MuiButtonBase-root MuiIconButton-root') and @tabindex = '0']
logout_button = //ul[@id = 'menu-list-grow']
Reschedule_class = //ul[@id = 'menu-list']/li/div/div/p[text()='Reschedule Class']
Cancel_Class = //ul[@id = 'menu-list']/div/li/div/div/p[text()='Cancel Class']
